DROP TABLE ODONTOLOGOS IF EXISTS;
DROP TABLE DOMICILIOS IF EXISTS;
DROP TABLE PACIENTES IF EXISTS;

CREATE TABLE ODONTOLOGOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
MATRICULA INT NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL
);

CREATE TABLE DOMICILIOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
CALLE VARCHAR(50) NOT NULL,
NUMERO INT NOT NULL,
LOCALIDAD VARCHAR(50) NOT NULL,
PROVINCIA VARCHAR(50) NOT NULL
);

CREATE TABLE PACIENTES(
ID INT AUTO_INCREMENT PRIMARY KEY,
APELLIDO VARCHAR(50) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
DNI VARCHAR(10) NOT NULL,
FECHA_INGRESO DATE NOT NULL,
ID_DOMICILIO INT NOT NULL
);

INSERT INTO ODONTOLOGOS VALUES(DEFAULT, 12345, 'ANDRES', 'FERRADA');
INSERT INTO ODONTOLOGOS VALUES(DEFAULT, 67890, 'ELIAS', 'HERNANDEZ');

INSERT INTO DOMICILIOS VALUES(DEFAULT, 'CALLE 1', 123, 'BUCARAMANGA', 'SANTANDER');
INSERT INTO PACIENTES VALUES(DEFAULT, 'PEREZ', 'JUAN', '12345678', '2024-08-21', 1);
INSERT INTO PACIENTES VALUES(DEFAULT, 'DETAL', 'FULANO', '5836478', '2024-08-22', 1);
